### ISSUE TITLE
Not working anymore for me since yesterday.

### ISSUE THREAD

**Issue by nigoki2** [alzamer2/Crunchyroll-XML-Decoder-py3#15]
Now Downloading - Ace of Diamond Episode 30 - Bloom of youth
Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 407, in <module>
    make_choise()
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 355, in make_choise
    ultimate()
  File "crunchy-xml-decoder\ultimate.py", line 190, in ultimate
    download_.video_hls(hls_url, video_input, config_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 143, in video_hls
    fetch_encryption_key(self.video)
  File "crunchy-xml-decoder\hls_.py", line 203, in fetch_encryption_key
    assert video.keys[0].method == 'AES-128'
AssertionError

I never had a problem with your script until now :(

**Comment by alzamer2** [comment]
Ok will try to see why Sent from Mail for Windows 10 From: nigoki2Sent: 23 October 2019 00:44To: alzamer2/Crunchyroll-XML-Decoder-py3Cc: SubscribedSubject: [alzamer2/Crunchyroll-XML-Decoder-py3] Not working anymore for me since yesterday. (#15) Now Downloading - Ace of Diamond Episode 30 - Bloom of youthTraceback (most recent call last):File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 407, in make_choise()File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 355, in make_choiseultimate()File "crunchy-xml-decoder\ultimate.py", line 190, in ultimatedownload_.video_hls(hls_url, video_input, config_['connection_n_'])File "crunchy-xml-decoder\hls_.py", line 143, in video_hlsfetch_encryption_key(self.video)File "crunchy-xml-decoder\hls_.py", line 203, in fetch_encryption_keyassert video.keys[0].method == 'AES-128'AssertionErrorI never had a problem with your script until now :(—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Askadelion** [comment]
the same error at me

**Comment by alzamer2** [comment]
sorry for delay
it seems crunchyroll changed their site again
they added multi-stream option other than AES-128 hls stream
that why the code was getting the wrong hls stream url (the code was getting encrypted hls stream for apple TV)
at least they added dash stream which can be downloaded too, so i added it as backup method in case hls stream download failed, but because i'm using youtube-dl to get dash stream i can speed download
ok i think i fixed it can you test it out

**Comment by nigoki2** [comment]
It works. Thank you very much for your time and work alzamer2  !

**Comment by alzamer2** [comment]
you are welcome
then i will close this issue
